const DEFAULT_PASS='AYKIRA@1234';
let products=[], settings={}, editingId=null, pendingImage=null, pendingColours=[], sessionPassword='';
const $=id=>document.getElementById(id);
function toast(t){$('toast').textContent=t;$('toast').style.display='block';setTimeout(()=>{$('toast').style.display='none'},1800)}
function defaultColours(image){return [1,2,3,4].map((n)=>({name:'Colour '+n,image:image||'',active:true}))}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function api(path,options={}){const r=await fetch(path,{cache:'no-store',...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});let d={};try{d=await r.json()}catch(_){}if(!r.ok)throw new Error(d.error||`Request failed (${r.status})`);return d}
async function seed(){const d=await api('/api/catalog');products=(d.products||[]).map(p=>({...p,colours:p.colours?.length?p.colours:defaultColours(p.image),customPricing:p.customPricing&&p.customPricing.enabled?{enabled:true,prices:{'18-22':Number(p.customPricing.prices?.['18-22'])||0,'24-32':Number(p.customPricing.prices?.['24-32'])||0,'34-38':Number(p.customPricing.prices?.['34-38'])||0}}:{enabled:false}}));settings=d.settings||{pricing:{'18-22':749,'24-32':999,'34-38':1199}}}
async function auth(){const pw=$('password').value;if(!pw){$('loginErr').textContent='Enter your password.';return}try{await api('/api/admin/login',{method:'POST',body:JSON.stringify({password:pw})});sessionPassword=pw;sessionStorage.setItem('aykira_admin_ok','1');$('login').classList.add('hidden');$('app').classList.remove('hidden');await seed();loadUI();loadOrders()}catch(e){$('loginErr').textContent=e.message||'Wrong password.'}}
function render(){const box=$('products');box.innerHTML='';products.forEach((p,i)=>{const el=document.createElement('div');el.className='item';el.innerHTML=`<img class="thumb" src="${p.image}" alt=""><div><h3>${esc(p.name)}</h3><div class="status ${p.available?'available':'stockout'}">${p.available?'Available':'Out of stock / hidden'}</div><div class="muted">${esc(p.description||'')}</div><div class="small">${(p.colours||[]).filter(c=>c.image&&c.active!==false).map(c=>esc(c.name)).join(' • ')}</div><div class="small" style="margin-top:6px">${p.customPricing?.enabled?`Custom: ₹${Number(p.customPricing.prices?.['18-22']||0)} / ₹${Number(p.customPricing.prices?.['24-32']||0)} / ₹${Number(p.customPricing.prices?.['34-38']||0)}`:'Default pricing'}</div></div><div class="actions"><button class="btn" data-act="edit" data-id="${p.id}">Edit</button><button class="btn" data-act="toggle" data-id="${p.id}">${p.available?'Mark Out of Stock':'Show Design'}</button><button class="btn" data-act="up" data-id="${p.id}" ${i===0?'disabled':''}>↑</button><button class="btn" data-act="down" data-id="${p.id}" ${i===products.length-1?'disabled':''}>↓</button><button class="btn danger" data-act="delete" data-id="${p.id}">Delete</button></div>`;box.appendChild(el)})}
function loadUI(){const pr=settings.pricing||{'18-22':749,'24-32':999,'34-38':1199};$('price1822').value=pr['18-22'];$('price2432').value=pr['24-32'];$('price3438').value=pr['34-38'];$('sEyebrow').value=settings.eyebrow||'';$('sTitle').value=settings.title||'';$('sLead').value=settings.lead||'';$('sCollection').value=settings.collection||'';$('sFestive').value=settings.festive||'';$('sSize').value=settings.size||'';render()}
function toggleCustomPricing(){const on=$('pCustomPricing')?.checked;const box=$('customPriceFields');if(box)box.style.opacity=on?'1':'.55';['pPrice1822','pPrice2432','pPrice3438'].forEach(id=>{if($(id))$(id).disabled=!on})}
function renderColours(){const box=$('colourEditor');box.innerHTML='';pendingColours=[0,1,2,3].map(i=>pendingColours[i]||{name:'Colour '+(i+1),image:'',active:true});pendingColours.forEach((c,i)=>{const active=c.active!==false;const el=document.createElement('div');el.className='colour-slot '+(active?'':'removed');el.innerHTML=`<h4>Colour ${i+1}</h4><input type="text" data-colour-name="${i}" value="${esc(c.name||'Colour '+(i+1))}" placeholder="e.g. Pink" ${active?'':'disabled'}><input type="file" accept="image/*" data-colour-file="${i}" ${active?'':'disabled'}><img id="colourPreview${i}" src="${c.image||''}" style="${c.image?'':'display:none'}" alt="Colour ${i+1} preview"><div class="colour-actions"><button type="button" class="btn ${active?'danger':'dark'}" data-colour-remove="${i}">${active?'Remove Colour':'Add/Restore Colour'}</button></div><p class="small">${active?'Visible on website':'Hidden from website — can be restored later.'}</p>`;box.appendChild(el)})}
function edit(p){editingId=p?.id||null;pendingImage=p?.image||null;pendingColours=(p?.colours?.length?p.colours:defaultColours(p?.image||'')).map(c=>({...c}));$('editorTitle').textContent=p?'Edit Design':'New Design';$('pName').value=p?.name||'';$('pDesc').value=p?.description||'';$('pAvailable').checked=p?p.available!==false:true;const cp=p?.customPricing?.enabled?p.customPricing.prices||{}:{};$('pCustomPricing').checked=!!p?.customPricing?.enabled;$('pPrice1822').value=cp['18-22']??(settings.pricing?.['18-22']??749);$('pPrice2432').value=cp['24-32']??(settings.pricing?.['24-32']??999);$('pPrice3438').value=cp['34-38']??(settings.pricing?.['34-38']??1199);toggleCustomPricing();$('preview').src=p?.image||'';$('preview').classList.toggle('hidden',!p?.image);$('pImage').value='';renderColours();$('editor').classList.remove('hidden');$('editor').scrollIntoView({behavior:'smooth'})}
async function saveAll(){const d=await api('/api/admin/save',{method:'POST',body:JSON.stringify({password:sessionPassword,products,settings})});if(!d.success)throw new Error('Save failed');const fresh=await api('/api/catalog');products=fresh.products||products;settings=fresh.settings||settings;return d} 
async function saveProductPriceDirect(product){
  const cp=product.customPricing||{};
  const d=await api('/api/admin/product-price',{method:'POST',body:JSON.stringify({password:sessionPassword,product_id:product.id,enabled:!!cp.enabled,prices:cp.prices||{}})});
  if(!d.success)throw new Error('Custom pricing save failed');
  const fresh=await api('/api/catalog');
  products=fresh.products||products; settings=fresh.settings||settings;
  return d;
}
$('loginBtn').onclick=auth;$('password').addEventListener('keydown',e=>{if(e.key==='Enter')auth()});$('logout').onclick=()=>{sessionStorage.removeItem('aykira_admin_ok');location.reload()};$('viewSite').onclick=()=>{location.href='/'};
async function loadOrders(){try{const d=await api('/api/admin/orders');const box=$('ordersBox');if(!box)return;const os=d.orders||[];box.innerHTML=os.length?os.map((o,i)=>`<div class="item" style="grid-template-columns:1fr auto;align-items:start"><div><h3>${esc(o.aykira_order_id)}</h3><div class="small">${esc(o.created_at||'')} · ${esc(o.payment_status||'pending')} · ${esc(o.status||'New')}</div><p class="small"><b>${esc(o.customer?.name||'')}</b> · ${esc(o.customer?.phone||'')}<br>${esc(o.customer?.address||'')}<br>${esc(o.customer?.city||'')}, ${esc(o.customer?.state||'')} — ${esc(o.customer?.pincode||'')}</p><div class="small">${(o.items||[]).map(x=>`${esc(x.name)} · ${esc(x.colour)} · Size ${esc(x.size)} × ${x.qty}`).join('<br>')}</div><p><b>₹${Number(o.amount||0)/100}</b></p></div><div class="actions"><select data-order-status="${esc(o.aykira_order_id)}"><option ${o.status==='New'?'selected':''}>New</option><option ${o.status==='Confirmed'?'selected':''}>Confirmed</option><option ${o.status==='Shipped'?'selected':''}>Shipped</option><option ${o.status==='Delivered'?'selected':''}>Delivered</option><option ${o.status==='Cancelled'?'selected':''}>Cancelled</option></select></div></div>`).join(''):'<p class="muted">No orders yet.</p>';}catch(e){alert(e.message||'Unable to load orders.')}}
$('refreshOrders')?.addEventListener('click',loadOrders);
$('ordersBox')?.addEventListener('change',async e=>{const s=e.target.closest('[data-order-status]');if(!s)return;try{await api('/api/admin/order-status',{method:'POST',body:JSON.stringify({password:sessionPassword,order_id:s.dataset.orderStatus,status:s.value})});toast('Order status updated')}catch(err){alert(err.message)}});$('newDesign').onclick=()=>edit(null);$('pCustomPricing')?.addEventListener('change',toggleCustomPricing);$('cancelEdit').onclick=()=>{$('editor').classList.add('hidden');pendingImage=null;pendingColours=[]};
$('pImage').onchange=e=>{const f=e.target.files[0];if(!f)return;if(f.size>8*1024*1024){alert('Please use an image under 8 MB.');e.target.value='';return}const rd=new FileReader();rd.onload=()=>{pendingImage=rd.result;$('preview').src=pendingImage;$('preview').classList.remove('hidden');if(!pendingColours.length)pendingColours=defaultColours(pendingImage);pendingColours[0].image=pendingImage;renderColours()};rd.readAsDataURL(f)};
$('colourEditor').addEventListener('input',e=>{const ni=e.target.dataset.colourName;if(ni!==undefined)pendingColours[Number(ni)].name=e.target.value});
$('colourEditor').addEventListener('change',e=>{const ni=e.target.dataset.colourFile;if(ni===undefined)return;const f=e.target.files[0];if(!f)return;if(f.size>8*1024*1024){alert('Please use an image under 8 MB.');e.target.value='';return}const rd=new FileReader();rd.onload=()=>{pendingColours[Number(ni)].image=rd.result;const im=$('colourPreview'+ni);im.src=rd.result;im.style.display='block'};rd.readAsDataURL(f)});
$('colourEditor').addEventListener('click',e=>{const b=e.target.closest('[data-colour-remove]');if(!b)return;const i=Number(b.dataset.colourRemove);if(!pendingColours[i])return;pendingColours[i].active=pendingColours[i].active===false;renderColours()});
$('saveProduct').onclick=async()=>{const name=$('pName').value.trim();if(!name){alert('Design name is required.');return}if(!pendingImage){alert('Please choose a main photo.');return}pendingColours=[0,1,2,3].map(i=>({name:(pendingColours[i]?.name||'Colour '+(i+1)).trim(),image:pendingColours[i]?.image||pendingImage,active:pendingColours[i]?.active!==false}));const customPricing=$('pCustomPricing').checked?{enabled:true,prices:{'18-22':Number($('pPrice1822').value)||0,'24-32':Number($('pPrice2432').value)||0,'34-38':Number($('pPrice3438').value)||0}}:{enabled:false};const obj={id:editingId||('d-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7)),name,description:$('pDesc').value.trim(),image:pendingImage,colours:pendingColours,available:$('pAvailable').checked,customPricing};if(editingId)products=products.map(p=>p.id===editingId?obj:p);else products.push(obj);try{await saveAll();const saved=products.find(p=>p.id===obj.id)||obj;await saveProductPriceDirect(saved);render();$('editor').classList.add('hidden');toast('Design + colours + pricing saved')}catch(e){alert(e.message)}};
$('products').onclick=async e=>{const b=e.target.closest('button');if(!b)return;const id=b.dataset.id,i=products.findIndex(p=>p.id===id);if(i<0)return;switch(b.dataset.act){case'edit':edit(products[i]);return;case'toggle':products[i].available=!products[i].available;break;case'delete':if(confirm('Delete this design?'))products.splice(i,1);else return;break;case'up':if(i>0)[products[i-1],products[i]]=[products[i],products[i-1]];break;case'down':if(i<products.length-1)[products[i+1],products[i]]=[products[i],products[i+1]];break}try{await saveAll();render();toast('Catalogue updated')}catch(e){alert(e.message)}};
$('saveSettings').onclick=async()=>{settings={...settings,eyebrow:$('sEyebrow').value,title:$('sTitle').value,lead:$('sLead').value,collection:$('sCollection').value,festive:$('sFestive').value,size:$('sSize').value};try{await saveAll();toast('Website text saved')}catch(e){alert(e.message)}};
$('savePricing').onclick=async()=>{settings.pricing={'18-22':Number($('price1822').value)||0,'24-32':Number($('price2432').value)||0,'34-38':Number($('price3438').value)||0};try{await saveAll();toast('Pricing saved')}catch(e){alert(e.message)}};
$('changePass').onclick=()=>alert('For security, change AYKIRA_ADMIN_PASSWORD in the server .env file, then restart the server.');
$('exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify({products,settings},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='aykira-catalogue-backup.json';a.click();URL.revokeObjectURL(a.href)};
$('importFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const rd=new FileReader();rd.onload=async()=>{try{const x=JSON.parse(rd.result);if(!Array.isArray(x.products))throw Error();products=x.products.map(p=>({...p,colours:p.colours?.length?p.colours:defaultColours(p.image),customPricing:p.customPricing&&p.customPricing.enabled?{enabled:true,prices:{'18-22':Number(p.customPricing.prices?.['18-22'])||0,'24-32':Number(p.customPricing.prices?.['24-32'])||0,'34-38':Number(p.customPricing.prices?.['34-38'])||0}}:{enabled:false}}));settings=x.settings||settings;await saveAll();loadUI();toast('Backup restored')}catch(err){alert('Invalid AYKIRA backup file.')}};rd.readAsText(f)};
(async()=>{try{await seed();if(sessionStorage.getItem('aykira_admin_ok')==='1'){sessionPassword=prompt('Enter AYKIRA admin password to continue:')||'';try{await api('/api/admin/login',{method:'POST',body:JSON.stringify({password:sessionPassword})});$('login').classList.add('hidden');$('app').classList.remove('hidden');loadUI();loadOrders()}catch(_){sessionStorage.removeItem('aykira_admin_ok')}}}catch(e){console.error(e)}})();
